version: '2'
services:
    supero-app:
        image: supero
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://supero-mariadb:3306/supero
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    supero-mariadb:
        extends:
            file: mariadb.yml
            service: supero-mariadb
